### PR TITLE
adding support for __thiscall to BIF_DllCall

### PR DESCRIPTION
**Pull request by mmikeww**
reference Helgef's improvement from this thread:
https://www.autohotkey.com/boards/viewtopic.php?p=265351#p265351

> new:
> specify thiscall for the return type to use calling convention __thiscall. Puts first argument in ecx register, except that, the behaviour is as __stdcall.
> 
> reference: https://docs.microsoft.com/en-us/cpp/cpp/thiscall?view=vs-2017
> 
> Reason, implementation is simple and this is difficult to achieve in script.

### CODE REVIEW

**Comment by HelgeffegleH** [comment]
There were some reasons why I didn't make the pull request myself, other than forgetting about it. At least I remember that supporting unquoted return type is unnecessary since it has been deprecated. Other considerations, should we enforce the first parameter to be ptr or atleast ptr-sized integer. I think gcc allows compiling thiscall with the first parameter as float, so that is weird. Should callbackcreate be updated to match? Probably something else I can't think of right now. 

__con__: probably one use case through out the entire existences of the language. And since 32 bit calling conventions are being less and less prevalent, I don't expect this to become very useful in the future. 

cheers.

**Comment by mmikeww** [comment]
Sorry about that Helgef. I did assume that perhaps you had just forgotten about this when I stumbled across it. I shouldn't have taken the liberty to submit on your behalf

**Comment by HelgeffegleH** [comment]
No need to apologise, as far as I'm concerned you made the pull request on your own behalf. I had forgot, I'm glad you reminded me. 

Cheers.

**Comment by Lexikos** [comment]
I've decided not to merge this, but for anyone who needs to call a *thiscall* function, I've demonstrated [how to call a thiscall function using machine code](https://www.autohotkey.com/boards/viewtopic.php?f=76&t=91105&p=402798#p402798).

**Pull request closed without merging**
