### PR TITLE
Implement dynamic function

### PR DESCRIPTION
**Pull request by HotKeyIt**
Add inline keyword for function definition to allow inline function.

### CODE REVIEW

**Comment by Lexikos** [comment]
Why?

**Comment by HotKeyIt** [comment]
Mainly to shorten repeating code.
Since this allows to use the variables in current scope, we can kind of "return"/set multiple variables and don't need a lot of parameters.

**Comment by Lexikos** [comment]
Using dynamic variables? Ugh.

If this is something I wanted in the language (it isn't), I would think it should be more explicit (at the point the variable is assigned/exported).

"Inline function" already has a meaning, and it's not this.

**Comment by HotKeyIt** [comment]
I see, yes the meaning is not the same but the effect is.
Unfortunately only when using dynamic variables, but I think it should be possible to allow to use the variables in current scope, right? Then it would do exactly the same as inline function does.

**Comment by Lexikos** [comment]
What? No, the effect is totally different. `inline` in C++ gives the compiler a suggestion to inline the function; to insert its implementation directly at the call site, as an optimisation. It generally does not affect the behaviour of the function at all, and is only a suggestion, which may have no effect.

On the other hand, this affects the behaviour of dynamic variable references (and A_ThisFunc?) inside the function, in a very non-obvious way.

I don't understand any part of your post beyond the first sentence.

**Comment by HotKeyIt** [comment]
Sorry, I completely confused myself with inline function and macro :(
What I had in mind is that the code would run as if it was not a function but 'gosub' in current scope similar to macro in c++ https://github.com/Lexikos/AutoHotkey_L/blob/master/source/script.h#L90.

**Comment by HotKeyIt** [comment]
How about to call it dynamic?
I think it is fine that A_ThisFunc is not reported or relates to the function that calls this function.
It would be great if all variables would be resolved at current scope but as I understand this would require to make them all dynamic and a lot of code would needs to be changed.
I think it is still great to be able to resolve at least dynamic variables to current scope.

**Comment by Lexikos** [comment]
That is no better. It doesn't make the function (more) dynamic. It doesn't make the variable references dynamic. They were already dynamic.

It does not resolve "dynamic variables to current scope". Inside the setvars/deref function, *current scope* is inside the setvars/deref function, as demonstrated by the fact that non-dynamic variables are local to that function. What it does is change dynamic variable references to use *the caller's* scope.

**Pull request closed without merging**
