### PR TITLE
v2: Changed SplitPath to return an object when no output parameters are passed.

### PR DESCRIPTION
**Pull request by jeeswg**
## Introduction

[Thoughts for v2.0](https://www.autohotkey.com/v2/v2-thoughts.htm)
> SplitPath could return an object when no output parameters are passed. Property names are probably easier to remember than parameter order, and easier to read and write than counting commas. This should have no negative impact on compatibility if added later, presuming scripts do not rely on SplitPath returning "".

This PR is an attempt at implementing this functionality.

The property names match those listed here:
[AutoHotkey v3.0-alpha.1 - Switching to JavaScript (not really) - AutoHotkey Community](https://autohotkey.com/boards/viewtopic.php?f=24&t=88821)
`Name, Dir, Ext, NameNoExt, Drive`.
My PR also includes a `Path` property, everything considered, I thought it worth including.

## An aside

I have submitted all the PRs I intend to, apart from these, to come in the next 7 days:
BinCompare/BinCopy.
InBuf. Find nth/nth-to-last occurrence.
BinDiff/StrDiff. 2 buffers/strings. Find nth/nth-to-last difference (byte/char).

# Test code

```
;==================================================

;test code: SplitPath: return object (AHK v2)

MsgBox()

;==================================================

vName := "abc"

SplitPath([])

SplitPath([], &vName)

MsgBox(vName)

SplitPath(0.123)

SplitPath(0.123, &vName)

MsgBox()

;==================================================

;test SplitPath to object:

;vPath := A_AhkPath
vPath := "C:\Program Files\AutoHotkey\AutoHotkey.exe"
oPath := SplitPath(vPath)

vOutput := ""
for vProp, vValue in oPath.OwnProps()
	vOutput .= vProp ": " vValue "`r`n`r`n"
A_Clipboard := vOutput
MsgBox(vOutput)

;==================================================

;test SplitPath still works with output variables:

SplitPath(vPath, &vName, &vDir, &vExt, &vNameNoExt, &vDrive)

vList := "Path,Name,Dir,Ext,NameNoExt,Drive"

vOutput := ""
for vKey, vValue in StrSplit(vList, ",")
	vOutput .= vValue ": " v%vValue% "`r`n`r`n"
A_Clipboard := vOutput
MsgBox(vOutput)
return

;==================================================

/*
e.g. output:

Dir: C:\Program Files\AutoHotkey

Drive: C:

Ext: exe

Name: AutoHotkey.exe

NameNoExt: AutoHotkey

Path: C:\Program Files\AutoHotkey\AutoHotkey.exe
*/

;==================================================
```

### CODE REVIEW

**Comment by Lexikos** [comment]
> SplitPath([])

What is this?

> vars[i] = new Var();

This is unacceptable. Aside from the unnecessarily hackish nature of allocating script vars to call a C++ function (i.e. instead of refactoring the code), it doesn't look like you ever delete the Vars.

**Comment by jeeswg** [comment]
`SplitPath([])` was testing whether `SplitPath` could handle certain types without an internal error or throwing.

IIRC it seemed a case of *use*/*duplicate*/*amend beyond recognition* the existing internal `SplitPath` function.
*Duplicating* would mean maintaining essentially the same thing in 2 places.
*Amending* (something I usually do) would have various downsides.
So I opted for *use*.
Hopefully the code would be useful as is, or save you time in finding a 4th approach.

**Comment by iseahound** [comment]
Since this doesn't seem intuitive, it's best to wait and see. 

1. Why does it return an object *if and only if* no parameters are passed? 
2. Should functions like `MonitorGet` and `MouseGetPos` with multiple returns also return objects?
3. Doesn't follow the robustness principle (Be conservative in what you do, be liberal in what you accept from others)

**Comment by jeeswg** [comment]
I'm going to released an improved version within the next few hours.

I appreciate your concerns, [iseahound](https://github.com/iseahound), I was implementing this suggestion, from here: [Thoughts for v2.0](https://www.autohotkey.com/v2/v2-thoughts.htm).

To answer your points, we needed an intuitive way to get one path substring. Currently, you only know which substring you're getting, based on the index of the parameter where you're placing a variable.
And perhaps some people wanted a way to get all path substrings.
This suggestion met those requirements.
We could have something like `PathGetPart(path, "NameNoExt")`, that would be an alternative.

Anyway, I intend to complete an improved PR, Lexikos can accept/amend/reject it/implement an alternative that fits with your concerns.

IMO there are other functions also, that use ByRef variables, that could output an object when given no parameters.

**Comment by Lexikos** [comment]
I do not think further interaction with you regarding this PR would be a productive use of my time.

**Pull request closed without merging**
