### PR TITLE
Suggestion regex object

### PR DESCRIPTION
**Pull request by nnnik**
This is how I would imagine the RegEx Object.
Make `Pos`, `Name`, `Value` etc. methods only and only allow get as a shorthand for `Value`.
That would put a clear border between what is a value and what isn't.
Bein able to differ between [] and . might also work out the same way.

### CODE REVIEW

**Comment by Vismund-Cygnus** [comment]
Is there a reason that a regex object returns 'true' when passed into IsObject() and yet does not work in a for-loop? Shouldn't a for-loop work for all objects?

**Comment by nnnik** [comment]
All objects that return an enumerator when their method _NewEnum is called support a for-loop.
For AHK built in objects thats actually only the associative array as far as Im aware.
And no it should not work for all objects.

**Comment by HelgeffegleH** [comment]
Also gui object support for loop.

**Comment by nnnik** [comment]
Well it may be good if regex objects support a for loop and were structured differently in general.
In my PR I focused on dividing between methods and properties and adding errors.
Maybe I should have made those 2 PRs too.

**Comment by Lexikos** [comment]
I'm confused. If I hover over the word `Closes` in the commit above, it says "This commit closes pull request #99."

But the pull request wasn't closed automatically...

**Pull request closed without merging**
