### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @Lexikos.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@Lexikos is something else needed for the PR to get merged?

**Comment by vedantmgoyal2009** [comment]
@Lexikos please merge the PR if everything seems fine...

**Comment by wmstack** [comment]
Hello, can I suggest that you add a WinGet non-administrator package as well? I want to install autohotkey without having to resort to using Scoop. I suggest a non-administrator option.

**Comment by vedantmgoyal2009** [comment]
cc @Lexikos

**Comment by Lexikos** [comment]
I am not going to blindly grant a third-party bot write access to my repository, and I lack the interest or motivation to look into this any further in the foreseeable future.

**Pull request closed without merging**
